import { TILE_DEST_SIZE, drawTile, drawCoin as spritesDrawCoin, createTilePattern } from '../assets/Sprites';
import { W, H, GROUND_Y } from '../utils/constants';

export const T = {
  AIR: 0,
  GROUND_TOP: 1,
  GROUND_FILL: 2,
  WALL: 3,
  PLATFORM: 4,
  CRATE: 5,
  METAL: 6,
  COIN: 7,
  ENEMY: 8,
};

const TS = TILE_DEST_SIZE;
const COLS = Math.ceil(W / TS) * 2 + 4;
const ROWS = Math.ceil(H / TS) + 2;

const CACHE_SIZE = 256;

const TERRAIN = {
  FLAT: 0,
  PLATFORM: 1,
  OBSTACLE: 2,
} as const;

function pick<T>(arr: T[]): T {
  return arr[Math.floor(Math.random() * arr.length)];
}

function randInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min;
}

export class Tilemap {
  /* Column cache: maps world column → column data (Uint8Array of ROWS entries) */
  private cache: Map<number, Uint8Array> = new Map();
  /* Track which columns have been fully generated by the FSM */
  private generatedUpTo: number = 0;
  private collected: Set<number> = new Set();
  readonly groundRow: number;

  private terrainState: number = TERRAIN.FLAT;
  private stateRemain: number = 0;
  private distSinceLastFlat = 0;

  /* Cached repeating patterns for the ground bands (undefined = not computed yet) */
  private groundTopPattern?: CanvasPattern | null;
  private groundFillPattern?: CanvasPattern | null;

  scrollOffset: number = 0;

  constructor() {
    this.groundRow = Math.floor(GROUND_Y / TS);
    this.pickNextState();
  }

  reset(): void {
    this.cache.clear();
    this.collected.clear();
    this.generatedUpTo = 0;
    this.terrainState = TERRAIN.FLAT;
    this.stateRemain = 0;
    this.distSinceLastFlat = 0;
    this.groundTopPattern = undefined;
    this.groundFillPattern = undefined;
    this.pickNextState();
  }

  /* Ensure column wc has been generated; lazy-generates from current FSM forward */
  private ensureCol(wc: number): void {
    while (this.generatedUpTo <= wc) {
      this.generateCol(this.generatedUpTo);
      this.generatedUpTo++;
    }
  }

  /* Generate one column of terrain and cache it */
  private generateCol(wc: number): void {
    if (this.stateRemain <= 0) {
      this.pickNextState();
    }
    this.stateRemain--;

    const data = new Uint8Array(ROWS);

    switch (this.terrainState) {
      case TERRAIN.FLAT:
        this.buildFlat(wc, data);
        break;
      case TERRAIN.PLATFORM:
        this.buildPlatform(wc, data);
        break;
      case TERRAIN.OBSTACLE:
        this.buildObstacle(wc, data);
        break;
    }

    this.cache.set(wc, data);

    /* Evict old columns beyond cache limit */
    if (this.cache.size > CACHE_SIZE) {
      const oldest = this.cache.keys().next().value;
      if (oldest !== undefined) {
        this.cache.delete(oldest);
        for (let r = 0; r < ROWS; r++) {
          this.collected.delete(oldest * ROWS + r);
        }
      }
    }
  }

  private buildFlat(_wc: number, data: Uint8Array): void {
    data[this.groundRow] = T.GROUND_TOP;
    for (let r = this.groundRow + 1; r < ROWS; r++) {
      data[r] = T.GROUND_FILL;
    }
    for (let r = 0; r < this.groundRow; r++) {
      data[r] = T.AIR;
    }
    if (Math.random() < 0.35) {
      data[this.groundRow - 1] = T.COIN;
    }
    const enemyChance = Math.min(0.12, 0.04 + this.scrollOffset / 10000);
    if (Math.random() < enemyChance) {
      data[this.groundRow - 2] = T.ENEMY;
    }
  }

  private buildPlatform(_wc: number, data: Uint8Array): void {
    this.buildFlat(_wc, data);
    const platRow = this.groundRow - randInt(3, 4);
    data[platRow] = T.PLATFORM;
    if (Math.random() < 0.7) {
      data[platRow - 1] = T.COIN;
    }
  }

  private buildObstacle(_wc: number, data: Uint8Array): void {
    this.buildFlat(_wc, data);
    data[this.groundRow - 1] = T.CRATE;
  }

  private pickNextState(): void {
    const prev = this.terrainState;
    this.distSinceLastFlat++;

    if (prev === TERRAIN.OBSTACLE) {
      this.terrainState = TERRAIN.FLAT;
      this.stateRemain = randInt(8, 18);
    } else if (prev === TERRAIN.PLATFORM) {
      this.terrainState = Math.random() < 0.5 ? TERRAIN.PLATFORM : TERRAIN.FLAT;
      this.stateRemain = this.terrainState === TERRAIN.PLATFORM ? randInt(3, 6) : randInt(6, 14);
    } else {
      /* FLAT */
      if (this.distSinceLastFlat < 5 && Math.random() < 0.7) {
        this.terrainState = TERRAIN.FLAT;
        this.stateRemain = randInt(8, 20);
      } else {
        this.distSinceLastFlat = 0;
        this.terrainState = pick([TERRAIN.PLATFORM, TERRAIN.OBSTACLE]);
        if (this.terrainState === TERRAIN.PLATFORM) this.stateRemain = randInt(3, 6);
        else this.stateRemain = randInt(2, 5);
      }
    }
  }

  /* ─── Public queries (x/y in SCREEN coordinates) ─── */

  private screenToWorld(screenX: number): number {
    return Math.floor((screenX + this.scrollOffset) / TS);
  }

  getTileAtCol(screenCol: number, y: number): number {
    const row = Math.floor(y / TS);
    if (row < 0 || row >= ROWS) return T.AIR;
    const worldCol = screenCol + Math.floor(this.scrollOffset / TS);
    this.ensureCol(worldCol);
    const data = this.cache.get(worldCol);
    return data ? data[row] : T.AIR;
  }

  getTileAt(x: number, y: number): number {
    const worldCol = this.screenToWorld(x);
    const row = Math.floor(y / TS);
    if (row < 0 || row >= ROWS) return T.AIR;
    this.ensureCol(worldCol);
    const data = this.cache.get(worldCol);
    return data ? data[row] : T.AIR;
  }

  isSolidAt(x: number, y: number): boolean {
    return this.isSolid(this.getTileAt(x, y));
  }

  isSolid(id: number): boolean {
    return id === T.GROUND_TOP || id === T.GROUND_FILL ||
           id === T.WALL || id === T.CRATE || id === T.METAL;
  }

  isPlatform(id: number): boolean {
    return id === T.PLATFORM;
  }

  isCoinAt(screenX: number, y: number): boolean {
    const worldCol = this.screenToWorld(screenX);
    const row = Math.floor(y / TS);
    if (row < 0 || row >= ROWS) return false;
    this.ensureCol(worldCol);
    const data = this.cache.get(worldCol);
    return data ? data[row] === T.COIN : false;
  }

  tryCollectCoin(screenX: number, y: number): boolean {
    const worldCol = this.screenToWorld(screenX);
    const row = Math.floor(y / TS);
    if (row < 0 || row >= ROWS) return false;
    this.ensureCol(worldCol);
    const data = this.cache.get(worldCol);
    if (!data || data[row] !== T.COIN) return false;
    const key = worldCol * ROWS + row;
    if (this.collected.has(key)) return false;
    this.collected.add(key);
    return true;
  }

  collectCoinsAt(screenX: number, y: number, radius: number): { wx: number; wy: number }[] {
    const result: { wx: number; wy: number }[] = [];
    const radiusSq = radius * radius;
    const centerCol = this.screenToWorld(screenX);
    const search = Math.ceil(radius / TS) + 1;
    for (let col = centerCol - search; col <= centerCol + search; col++) {
      this.ensureCol(col);
      const data = this.cache.get(col);
      if (!data) continue;
      for (let r = 0; r < ROWS; r++) {
        if (data[r] !== T.COIN) continue;
        const key = col * ROWS + r;
        if (this.collected.has(key)) continue;
        const coinWX = col * TS + TS / 2;
        const coinSY = r * TS + TS / 2;
        const coinSX = coinWX - this.scrollOffset;
        const dx = screenX - coinSX;
        const dy = y - coinSY;
        if (dx * dx + dy * dy < radiusSq) {
          this.collected.add(key);
          result.push({ wx: coinWX, wy: coinSY });
        }
      }
    }
    return result;
  }

  collectEnemiesAt(screenX: number, y: number, radius: number): { wx: number; wy: number }[] {
    const result: { wx: number; wy: number }[] = [];
    const radiusSq = radius * radius;
    const centerCol = this.screenToWorld(screenX);
    const search = Math.ceil(radius / TS) + 1;
    for (let col = centerCol - search; col <= centerCol + search; col++) {
      this.ensureCol(col);
      const data = this.cache.get(col);
      if (!data) continue;
      for (let r = 0; r < ROWS; r++) {
        if (data[r] !== T.ENEMY) continue;
        const key = col * ROWS + r;
        if (this.collected.has(key)) continue;
        const wx = col * TS + TS / 2;
        const sy = r * TS + TS / 2;
        const sx = wx - this.scrollOffset;
        const dx = screenX - sx;
        const dy = y - sy;
        if (dx * dx + dy * dy < radiusSq) {
          this.collected.add(key);
          data[r] = T.AIR;
          result.push({ wx, wy: sy });
        }
      }
    }
    return result;
  }

  removeTileAt(screenX: number, y: number): void {
    const worldCol = this.screenToWorld(screenX);
    const row = Math.floor(y / TS);
    if (row < 0 || row >= ROWS) return;
    this.ensureCol(worldCol);
    const data = this.cache.get(worldCol);
    if (data) data[row] = T.AIR;
  }

  getRows(): number { return ROWS; }
  getCols(): number { return COLS; }
  getWorldCol(): number { return 0; }
  getGroundRow(): number { return this.groundRow; }

  /* ─── Rendering (tiles offset by -scrollOffset so world scrolls left) ─── */

  draw(ctx: CanvasRenderingContext2D): void {
    const scrollOff = this.scrollOffset;
    const viewLeft = Math.floor((scrollOff - 50) / TS);
    const viewRight = Math.ceil((scrollOff + W + 50) / TS);

    /* Batch the two ground bands into 2 fillRect calls (was ~6 drawImages per column) */
    if (this.groundTopPattern === undefined) this.groundTopPattern = createTilePattern(ctx, 'ground_top');
    if (this.groundFillPattern === undefined) this.groundFillPattern = createTilePattern(ctx, 'ground_fill');
    const batched = this.groundTopPattern !== null && this.groundFillPattern !== null;
    if (batched) {
      const px = Math.round(viewLeft * TS - scrollOff);
      const width = (viewRight - viewLeft + 1) * TS;
      ctx.fillStyle = this.groundFillPattern!;
      ctx.fillRect(px, (this.groundRow + 1) * TS, width, H - (this.groundRow + 1) * TS + 1);
      ctx.fillStyle = this.groundTopPattern!;
      ctx.fillRect(px, this.groundRow * TS, width, TS);
    }

    for (let col = viewLeft; col <= viewRight; col++) {
      this.ensureCol(col);
      const data = this.cache.get(col);
      if (!data) continue;
      for (let r = 0; r < ROWS; r++) {
        const id = data[r];
        if (id === T.AIR || id === T.COIN) continue;
        if (batched && (id === T.GROUND_TOP || id === T.GROUND_FILL)) continue;
        const name = this.tileName(id);
        if (name) drawTile(ctx, name, col * TS - scrollOff, r * TS, TS, TS);
      }
    }
  }

  drawCoins(ctx: CanvasRenderingContext2D): void {
    const scrollOff = this.scrollOffset;
    const viewLeft = Math.floor((scrollOff - 50) / TS);
    const viewRight = Math.ceil((scrollOff + W + 50) / TS);
    for (let col = viewLeft; col <= viewRight; col++) {
      this.ensureCol(col);
      const data = this.cache.get(col);
      if (!data) continue;
      for (let r = 0; r < ROWS; r++) {
        if (data[r] !== T.COIN) continue;
        const key = col * ROWS + r;
        if (this.collected.has(key)) continue;
        const dx = col * TS - scrollOff + TS / 2;
        const dy = r * TS + TS / 2;
        const wobble = Math.sin(performance.now() * 0.004 + dx) * 2;
        spritesDrawCoin(ctx, dx, dy, 8, wobble);
      }
    }
  }

  private tileName(id: number): string | null {
    switch (id) {
      case T.GROUND_TOP: return 'ground_top';
      case T.GROUND_FILL: return 'ground_fill';
      case T.WALL: return 'wall';
      case T.PLATFORM: return 'platform';
      case T.CRATE: return 'crate';
      case T.METAL: return 'metal';
      default: return null;
    }
  }
}
